services:
  nginx:
    build: ./nginx
    image: my-nginx
    container_name: nginx-container
    ports:
      - "8080:80"
    networks:
      - express-network
    depends_on:
      - express-app
  express-app:
    build: 
      context: .
    image: my-express-app
    container_name: express-container
    networks:
      - express-network
networks:
  express-network:
    driver: bridge
